### ISSUE TITLE
step where action clones Wesnoth repo prints "`fatal:`" warnings

### ISSUE THREAD

**Issue by cooljeanius** [czyzby/wesnoth-wml-linter#7]
This message looks rather concerning:
```
Cloning Wesnoth 1.16.10.
Cloning into '/wesnoth'...
fatal: specify directories rather than patterns.  If your directory really has any of '*?[]\' in it, pass --skip-checks
Wesnoth repository is ready.
```
It doesn't actually cause any failures, though, so I guess it's more just of an annoyance than anything... still, it might be worth trying to pass the `--skip-checks` flag to whatever printed that message anyways, though?

**Comment by czyzby** [comment]
Interesting. I'm pretty sure that error wasn't being shown when I implemented those actions, although GitHub has removed old builds and I'm unable to access the logs. I'll try to look into it after the holidays.

**Comment by czyzby** [comment]
Looks like recent Git versions default to the `cone` mode that does only supports directories rather than individual files or patterns. `--no-cone` should do it. Thanks for reporting this issue.

**Comment by czyzby** [comment]
The error should no longer occur when using `v1` or `latest` releases. Thanks.

**Comment by cooljeanius** [comment]
> The error should no longer occur when using `v1` or `latest` releases. Thanks.

Shouldn't the version number be incremented to reflect that there's been a change? That would also help Dependabot pick it up

**Comment by czyzby** [comment]
@cooljeanius It was, the latest release with the bugfix is 1.5.1. GitHub actions seem to follow this convention where major versions (e.g., `v1`) point to the latest compatible stable release for convenience of pipelines maintenance. That way all repositories that use the `v1` release are automatically updated. If you'd like to freeze your pipelines at a specific version, you can use `v1.5.1` instead, but I don't necessarily recommend it - I'd like to avoid introducing breaking changes without incrementing the major version first either way.

**Comment by cooljeanius** [comment]
ah, got it, thanks
