### ISSUE TITLE
Directory spellings for wmllint

### ISSUE THREAD

**Issue by konecnyjakub** [czyzby/wesnoth-wml-linter#9]
I just started using this action for one add-on I maintain. It was working just like I expected until I enabled spellchecker for wmllint, then it started printing a lot of "possible misspellings" errors: https://github.com/konecnyjakub/Danse_Macabre/actions/runs/10062036175/job/27813540274. They should not be printed as all these words are added to dictionary with comments `# wmllint: directory spellings ...`. When I run wmllint locally, I do not get these errors. Is there any way to fix this? For completeness's sake, I use this configuration for the action: https://github.com/konecnyjakub/Danse_Macabre/blob/d162bcb2103d8b002d1188da54dd5fa064acd749/.github/workflows/lint.yml.

**Comment by czyzby** [comment]
Try adding them to the dictionary, see [this](https://github.com/czyzby/wesnoth-saurian-pack/blob/main/_main.cfg#L68) config for an example.

**Comment by konecnyjakub** [comment]
They are in dictionary: https://github.com/konecnyjakub/Danse_Macabre/blob/282cbf14db84fde163fadcbfa7440f343ddeee63/_main.cfg#L7, I just use (in all add-ons I maintain) dictionary spellings instead of general spellings. According to comments in wmllint, these should work:

> A magic comment of the form "wmllint: general spellings word1
> word2..."  will declare the tokens word1, word2, etc. to be
> acceptable spellings for anywhere in the Wesnoth tree that the
> spellchecker should never flag.  If the keyword "general" is
> replaced by "local", the spelling exceptions apply only in the
> current file. If the keyword "general" is replaced by "directory",
> the spelling exceptions apply to all files below the parent
> directory.

When I use general spellings, there are no errors (I tried that on a branch). I was just wondering why this does not work in GitHub actions when it works on my machine (where I normally run wmllint via Maintenance tools GUI).

**Comment by czyzby** [comment]
I'm afraid `wmllint` maintainer(s) would have more answers. My best guess is that when you run it locally, you're doing so on a complete Wesnoth installation with only your add-on directory as input. To speed things up, the GitHub action does a partial checkout of the Wesnoth repository and has to include its core folder as one of the inputs for the macros (etc.) to be picked up correctly. There might be a bug in `wmlllint` that prevents directory spelling definitions from working when there are multiple inputs.

**Comment by soliton-** [comment]
If you give wmllint `.` to check then top-level files have no path as you can see in the output. For directory spellings an empty path is not considered.

As a workaround you can give a path with a dir name. Absolute paths like $PWD won't work with this action though since it filters out messages for absolute paths presumably assuming they're from wesnoth data. Something like `../Danse_Macabre` should work though.

**Comment by konecnyjakub** [comment]
@soliton- I didn't know wmllint treats `.` that way. Thanks for the info. Unfortunately that workaround didn't work (I removed all my directory spellings and it didn't report any possible misspellings). Maybe I will look into it deeper later.

@czyzby I found out the cause of the error so I think this issue can be closed. I will use general spellings for now.
